Import.

In [6]:
import numpy as np
import pandas as pd

Read input data.

In [7]:
def readData(fileName):
    file = open(fileName, "r")
    matrix = []
    for line in file:
        matrix.append(np.array([int(i) for i in line.split()]))
    file.close()
    return np.array(matrix)

Function for total count normalization.

In [8]:
def totalCountNormalization(matrix):
    return matrix / matrix.sum(axis=0)

Numeric test:

In [9]:
matrix = readData('dataset.txt')
print("Before =\n", matrix, end='\n\n')
normal_matrix = totalCountNormalization(matrix)
print("After =\n", normal_matrix)

Before =
 [[  5  10   1]
 [ 10  20   2]
 [  1   2   5]
 [353   0   2]
 [  7   7   7]
 [  9   9   9]
 [  8   9   8]
 [  1   4   1]]

After =
 [[ 0.01269036  0.16393443  0.02857143]
 [ 0.02538071  0.32786885  0.05714286]
 [ 0.00253807  0.03278689  0.14285714]
 [ 0.89593909  0.          0.05714286]
 [ 0.0177665   0.1147541   0.2       ]
 [ 0.02284264  0.14754098  0.25714286]
 [ 0.02030457  0.14754098  0.22857143]
 [ 0.00253807  0.06557377  0.02857143]]


Performance test:

In [11]:
matrix = np.random.randint(0, 1000, size=(3000, 5000))

print("totalCountNormalization - ", end="")
%time normal_matrix = totalCountNormalization(matrix)

totalCountNormalization - Wall time: 148 ms


Read matrix from .csv file and normalization it:

In [12]:
data = pd.read_csv("srr1784310_subset.csv")
print(data.head())
normal_data = pd.DataFrame(totalCountNormalization(np.array(data.iloc[:, 1:])))
print(normal_data.head())

   Unnamed: 0  AGCACCTCTAAGCTTCT  GAGACAGATACGCTAGTC  CCAACCGTCGATTGAT  \
0  uc009vfc.1                 49                  50                48   
1  uc009vew.1                 50                  45                57   
2       Lars2                 90                 110                89   
3    Hsp90ab1                143                 103               104   
4        Ptma                 67                 136                85   

   TGATATTGCCTAACAATCC  ATATGCATACTAGGAT  GACTAGACCCAAACGCCT  \
0                   33                47                  42   
1                   28                72                  59   
2                  113                77                  81   
3                  112               111                  90   
4                   66                96                  73   

   ACCTTGCCAAACCTCC  GATGACCCTCACCTTGCC  AATATACCTATATGCAT        ...         \
0                40                  21                171        ...          
1         