In [1]:
import numpy as np
import pandas as pd

In [16]:
base_log = 2

In [15]:
matrix = np.random.randint(0, 10, size=(8, 3))
count_columns = matrix.shape[1]
matrix

array([[1, 4, 0],
       [6, 5, 8],
       [8, 1, 9],
       [3, 8, 7],
       [7, 2, 6],
       [8, 9, 7],
       [5, 7, 6],
       [5, 5, 4]])

## mean estimation

In [8]:
K = matrix[~np.any(matrix == 0, axis=1)]
K_R = np.array([np.prod(row) for row in K]) ** (1/count_columns)
Sj = np.median( K.T / K_R , axis=1)
Sij = Sj

Qij = base_log ** (1)

MUij = Sij * Qij

K, K_R

(array([[1, 7, 7],
        [1, 2, 7],
        [3, 3, 2],
        [7, 6, 8],
        [7, 7, 5]]),
 array([3.65930571, 2.41014226, 2.62074139, 6.95205329, 6.25732475]))

In [14]:

MUi = np.sum(K / Sij, axis=1) / count_columns
Sj, MUi

(array([1.00689677, 1.11868894, 1.15073917]),
 array([4.44450728, 2.95466806, 2.46639178, 6.42250926, 5.85147045]))